#!/usr/bin/env perl
use strict;
use warnings;

die qx{perldoc $0} unless @ARGV >= 2;
my $cmd = sprintf q{bundle exec rake new_%s["%s"]}, shift @ARGV, join ' ', @ARGV;
my ($file) = qx{$cmd} =~ m/Creating new post: (.*)/;
exec $ENV{VISUAL} || $ENV{EDITOR}, $file if $file;


=head1 USEAGE

  new post about something
  new page about me

=cut
